### ISSUE TITLE
Average temp values for smoother graphs

### ISSUE THREAD

**Issue by jaatuli** [o0Zz/ha-melcloud#1]
This component works great, but one thing I've been thinking is smoother graphs for the temp values. 
![image](https://user-images.githubusercontent.com/15844851/46906557-f1059700-cf0d-11e8-8a8c-48b248381349.png)

Currently the output is something like this. I've built my sensors to average to .1 C. So for this average over 10 values would also do the trick. This may not be for everyone. I have very little experience in Python and ha-framework, but I think I could get this done, if you could suggest some ideas where to put it.

**Comment by jaatuli** [comment]
Implemented in #2

**Comment by o0Zz** [comment]
Thanks, your implementation has been merged
