### ISSUE TITLE
doesnt work with HA 0.95.1

### ISSUE THREAD

**Issue by mjpswe** [o0Zz/ha-melcloud#13]
Updated to latest HA today and after that the component stop working, doesnt lookslike it has any contact with Melcloud server anymore

**Comment by CookieMonster87** [comment]
No issues on 95.1 for me. Are you using the latest files?

**Comment by mjpswe** [comment]
I have copied the latest file(climate.py) from here yesterday and still the same error: Entity not available
Upgraded to 0.95.4 now same error

**Comment by mjpswe** [comment]
Get this when I use Check Config:

Integration melcloud not found when trying to verify its climate platform.

Havent changed anything else then the climate.py

**Comment by mjpswe** [comment]
Works again, dont know why, havent changed anything
