### ISSUE TITLE
Climate Cleanup in hass 0.96 Breaking change

### ISSUE THREAD

**Issue by CookieMonster87** [o0Zz/ha-melcloud#15]
@o0Zz 
Component need to be updated to work with version 0.96 releasing this week. Multiple breaking changes 

https://developers.home-assistant.io/blog/2019/07/03/climate-cleanup.html
https://github.com/home-assistant/home-assistant/pull/23899

**Comment by dolenec** [comment]
Is there any news regarding component update?

**Comment by o0Zz** [comment]
Hi,

I'm working on it. I will need probably more time to integrate the changes but it's in progress. I will keep you updated in this ticket.

BR

**Comment by mgosk** [comment]
Do you have list of things to fix ? I'm not very familiar with python, but I will try to help :)

**Comment by o0Zz** [comment]
I updated this component to be compatible with new HA v0.96. Please have a look and let me know if everything is correct.

**Comment by CookieMonster87** [comment]
Thanks @o0Zz
I updated now. But only one heatpump. I have two. It worked for both before. Any changes that may have broken that? I see both in Melcloud app.

Also get this error:
name ‘OPERATION_COOL_STR’ is not defined

**Comment by EDV11** [comment]
@oOZz

Thanks for your work

@CookieMonster87

Care to share your updated files?

Thanks

**Comment by MuppetOwl** [comment]
Updated changes is already applied. I created a pull request that o0Zz added to the latest version of the file.
