### ISSUE TITLE
Entity is found, login works but not shown in hass

### ISSUE THREAD

**Issue by echo-devnull** [o0Zz/ha-melcloud#22]
So the melcloud plugin finds the entity:

```
hvac_modes:
  - heat
  - cool
  - dry
  - fan_only
  - auto
  - 'off'
current_temperature: 22
min_temp: 16
max_temp: 30
temperature: 16
fan_mode: Speed 2
fan_modes:
  - Speed Auto
  - Speed 1 (Min)
  - Speed 2
  - Speed 3
  - Speed 4 (Max)
swing_mode: Auto
swing_modes:
  - Auto
  - Top
  - MiddleTop
  - Middle
  - MiddleBottom
  - Bottom
  - Swing
friendly_name: MELCloud Micah's Airco (----)
supported_features: 41
```

But it does not appear in the hass website / overview page.  Anything I need to do to "enable" that part?

Thanks in advance man!

**Comment by dolenec** [comment]
Check this topic:
https://community.home-assistant.io/t/mitsubishi-melcloud-integration-with-home-assistant/26275/196

**Comment by echo-devnull** [comment]
Hi @dolenec , I did! That's how I found this plugin. But I must be missing some information then? Is it not possible or am I not seeing the config in the 219 posts there?

**Comment by dolenec** [comment]
Check post 220. Just replace with correct entity ID and sensors and you are done.
In case that entity is not found then you probably need to restart Melcloud and check that via Melcloud app on phone is working + probably try to make HA restart..

**Comment by dolenec** [comment]
'+ never, I mean NEVER publish climate ID.. it's dangerous..

**Comment by dolenec** [comment]
Sorry.. check post 221. I forgot to add something..
