### ISSUE TITLE
integration will no longer be loaded

### ISSUE THREAD

**Issue by erikwachters** [o0Zz/ha-melcloud#23]
Hello,

I have this in my logs. Is it true? :)

` [homeassistant.loader] No 'version' key in the manifest file for custom integration 'melcloud'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'melcloud'`

thx

E.

EDIT: Never mind, found my problem......

**Comment by o0Zz** [comment]
Hi,

This integration is no more supported since Homeassistant did an official integration available here: https://www.home-assistant.io/integrations/melcloud/

Thanks
