### ISSUE TITLE
Wont work in NZ

### ISSUE THREAD

**Issue by ethicallymad** [o0Zz/ha-melcloud#25]
The Aus/NZ Mitsubishi heat pumps use a different app, though very similar. (Mel Cloud is not available here)

Is there anyway to login to the NZ official app to get the same data/control?

Cheers

**Comment by o0Zz** [comment]
Hi,

This integration is no more supported since Homeassistant did an official integration available here: https://www.home-assistant.io/integrations/melcloud/

I think you should report the issue to them.

Thanks
