### ISSUE TITLE
Timer getting out of sync

### ISSUE THREAD

**Issue by Argo8** [o0Zz/ha-melcloud#3]
Hello,
After installing i get this issue in HA log:
Timer got out of sync. Resetting
5:32 PM core.py (ERROR)

It happens once a minute. Exacly one time every minute. 
When i disable melcloud it goes away. Have you any idea whats causing it?

**Comment by o0Zz** [comment]
Hum very strange, never see that in the past, can you still reproduce it ? If yes, could you please provide melcloud logs at the same time
