### ISSUE TITLE
Don't refresh on homekit

### ISSUE THREAD

**Issue by risky2000** [o0Zz/ha-melcloud#4]
In HA UI works fine, but if you use HomeKit integration, the devices state doesn't refresh in Home App.

**Comment by o0Zz** [comment]
I don't have any homekit to reproduce this issue, but i'm using normal homeassistant flow so it should work. If you have more details regarding this issue, let me know,

**Comment by o0Zz** [comment]
No more details regarding this issue, as soon as you have more information please re-open this ticket.
