### ISSUE TITLE
Object has no attribute 'unique_id'

### ISSUE THREAD

**Issue by dolenec** [o0Zz/ha-melcloud#5]
![53959966-550b4080-40e5-11e9-8f16-a22bfc15be72](https://user-images.githubusercontent.com/16633222/53974661-521f4880-4103-11e9-916b-8805e9e4df60.png)
Original post which was closed because this is not officialy supported:
https://github.com/home-assistant/home-assistant/issues/21741

Home Assistant release with the issue:

melcloud

Last working Home Assistant release (if known):
0.88.2

Operating environment (Hass.io/Docker/Windows/etc.):
Hass.io

Component/platform:
melcloud.climate
https://community.home-assistant.io/t/mitsubishi-melcloud-integration-with-home-assistant/26275
https://github.com/o0Zz/ha-melcloud/

Description of problem:
Before was working. Now is problem:
AttributeError: 'MelCloudClimate' object has no attribute 'unique_id'

Problem-relevant configuration.yaml entries and (fill out even if it seems unimportant):

Traceback (if applicable):
/

Additional information:
Log Details (ERROR)
Thu Mar 07 2019 14:07:21 GMT+0100 (Central European Standard Time)
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 257, in _async_add_entity
if entity.unique_id is not None:
AttributeError: 'MelCloudClimate' object has no attribute 'unique_id'

_This is a custom component, this bug tracker is only for official components. Please raise the issue with the author of the component._

**The issue likely is this line:**
https://github.com/o0Zz/ha-melcloud/blob/master/custom_components/climate/melcloud.py#L68
The location of the ClimateDevice class has changed.

**Comment by markimf** [comment]
Hi,
I managed to fix the issue in my server only separating the libraries import part:
        
       from homeassistant.components.climate.const import (SUPPORT_TARGET_TEMPERATURE, SUPPORT_FAN_MODE, SUPPORT_OPERATION_MODE, SUPPORT_ON_OFF, SUPPORT_SWING_MODE)
       from homeassistant.components.climate import ClimateDevice

The constants are in the .homeassistant.components.climate.const now. and the ClimateDevice class is still in the __init__.py part.

At least my server is connecting to MELcloud correctly now.

**Comment by dolenec** [comment]
So.. where I can get the latest code?

**Comment by markimf** [comment]
I submitted a pull request to fix the issue. As I'm not maintainer of the project, so I can't commit the changes. For those which can touch the code, the instructions above should fix it.

**Comment by CookieMonster87** [comment]
I have fixed the issue is this fork
https://github.com/CookieMonster87/pymelcloud

**Comment by o0Zz** [comment]
Thanks to markimf it's fixed
