### ISSUE TITLE
After upgrade Home Assistant to 0.92.0

### ISSUE THREAD

**Issue by LainX84** [o0Zz/ha-melcloud#8]
Integration melcloud not found when trying to verify its climate platform.
 components/hassio/__init__.py (ERROR) - message first occured at 11:08 and shows up 3 times

**Comment by CookieMonster87** [comment]
You need to create a empty __init__.py file in the Melcloud folder. Breaking change in the release notes for 0.92.0

**Comment by LainX84** [comment]
Do It, i've create empity init.py bit the issue Is not solve

**Comment by CookieMonster87** [comment]
it must be named like this `__init__.py`
You can also try to remove the pycache folder.

**Comment by detxm80** [comment]
removed pycache folder solved the issue for me, init.py file already exists

**Comment by detxm80** [comment]
@CookieMonster87 there is a way to put this custom component in custom updater? 

What is the difference with your version and o0Zz version? Thanks

**Comment by LainX84** [comment]
Upgrade HA to 0.92.1 and now melcloud turn back to work correctly.
Additional alert in the logs :

You are using a custom integration for melcloud which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.

Updating state for climate.melcloud_camera_matteo_120175 (<class 'custom_components.melcloud.climate.MelCloudClimate'>) took 0.507 seconds. Please report platform to the developers at https://goo.gl/Nvioub

Updating state for climate.melcloud_camera_genitori_120176 (<class 'custom_components.melcloud.climate.MelCloudClimate'>) took 0.420 seconds. Please report platform to the developers at https://goo.gl/Nvioub

Updating state for climate.melcloud_cucina_120180 (<class 'custom_components.melcloud.climate.MelCloudClimate'>) took 0.428 seconds. Please report platform to the developers at https://goo.gl/Nvioub

**Comment by LainX84** [comment]
Upgrade HA to 0.92.1 and now melcloud turn back to work correctly.
Additional alert in the logs :

You are using a custom integration for melcloud which has not been
tested by Home Assistant. This component might cause stability
problems, be sure to disable it if you do experience issues with Home
Assistant.

Updating state for climate.melcloud_camera_matteo_120175 (<class
'custom_components.melcloud.climate.MelCloudClimate'>) took 0.507
seconds. Please report platform to the developers at
https://goo.gl/Nvioub

Updating state for climate.melcloud_camera_genitori_120176 (<class
'custom_components.melcloud.climate.MelCloudClimate'>) took 0.420
seconds. Please report platform to the developers at
https://goo.gl/Nvioub

Updating state for climate.melcloud_cucina_120180 (<class
'custom_components.melcloud.climate.MelCloudClimate'>) took 0.428
seconds. Please report platform to the developers at
https://goo.gl/Nvioub


Il giorno gio 25 apr 2019 alle ore 21:29 detxm80 <notifications@github.com>
ha scritto:

**Comment by aravndal** [comment]
Included the following files in the melcloud directory to get it working.

**__init__.py**:
"""The Melcloud integration."""

**manifest.json**:
{
  "domain": "melcloud",
  "name": "Melcloud",
  "documentation": "https://github.com/o0Zz/ha-melcloud/",
  "dependencies": [],
  "codeowners": ["@o0zz"],
  "requirements": ["requests"]
}

**Comment by o0Zz** [comment]
@aravndal Thank you for your support. I added these 2 files to the repo.

**Comment by zazza1973** [comment]
Hi all, thanx for the hints.
I fixed it with version 97.b1 when I put the CASE of the folder equal to that in the manifest and in the configuration.yaml
