### ISSUE TITLE
Change swing list from number to names

### ISSUE THREAD

**Issue by CookieMonster87** [o0Zz/ha-melcloud#9]
I think the Swing list should be changed to names. Auto, Top, MiddleTop, Middle, MiddleBottom and Swing.
That is the same as used for other climate components like Sensibo Sky. 

Line: 420
self._swing_list = ['Auto', 'Top', 'MiddleTop', 'Middle', 'MiddleBottom', 'Bottom', 'Swing']

**Comment by o0Zz** [comment]
Thanks for your report, I integrated this change in last commit: f22f3d188b6b731ad43ca8589e68575a8cf3af54
